
---
- name: Ensuring OS is supported by the automation
  fail:
    msg: "Setup execution failed because the {{ ansible_os_family }} is not supported"
  when: >
    ansible_os_family != "Debian" and
    ansible_os_family != "RedHat"
